# Generated by Django 4.0.2 on 2022-03-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_comm_feedback_commenters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='commenters',
        ),
    ]
