# Generated by Django 4.0.2 on 2022-03-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_feedback_commenters'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='details',
            field=models.CharField(default='SOME STRING', max_length=600),
        ),
    ]
