# Generated by Django 4.0.2 on 2022-03-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_feedback_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rigester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
