# Generated by Django 4.0.2 on 2022-03-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_password_rigester_password1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='rigester',
            name='Username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
